=== alphasigma25/SER_Labo1/src/echecs.dtd
<!ELEMENT Organisation (Nom, Joueurs, Arbitres, ListeTournois)>
        <!ELEMENT Nom (#PCDATA)>
        <!ELEMENT Joueurs (Joueur+)>
        <!ELEMENT Joueur (noAVS, Nom, Prenom, ELO)>
        <!ATTLIST Joueur noAVS ID #REQUIRED>
        <!ELEMENT noAVS (#PCDATA)>
        <!ELEMENT Prenom (#PCDATA)>
        <!ELEMENT ELO (#PCDATA)>
        <!ELEMENT Arbitres (Arbitre+)>
        <!ELEMENT Arbitre (Nom, Prenom)>
        <!ATTLIST Arbitre id ID #REQUIRED>
        <!ELEMENT ListeTournois (ArbitresRef, Tournois*)>
        <!ELEMENT ArbitresRef (ArbitreRef+)>
        <!ELEMENT ArbitreRef EMPTY>
        <!ATTLIST ArbitreRef arbitreId IDREF #REQUIRED>
        <!ELEMENT Tournois (Nom, Equipes, Parties, Vainqueur)>
        <!ATTLIST Tournois idTournois ID #REQUIRED>
        <!ELEMENT Equipes (Equipe, Equipe)>
        <!ELEMENT Equipe (Nom, JoueursRef)>
        <!ATTLIST Equipe id ID #REQUIRED>
        <!ELEMENT JoueursRef (JoueurRef, JoueurRef)>
        <!ELEMENT JoueurRef EMPTY>
        <!ATTLIST JoueurRef joueurId IDREF #REQUIRED>
        <!ELEMENT Parties (Partie+)>
        <!ELEMENT Partie (Date, Heure, ArbitreRef, Echiquiers, Score)>
        <!ELEMENT Date (#PCDATA)>
        <!ELEMENT Heure (#PCDATA)>
        <!ELEMENT Echiquiers (Echiquier, Echiquier)>
        <!ELEMENT Echiquier ((premier|deuxieme), JoueurBlanc, JoueurNoir, Coups)>
        <!ELEMENT premier EMPTY>
        <!ELEMENT deuxieme EMPTY>
        <!ELEMENT JoueurBlanc EMPTY>
        <!ATTLIST JoueurBlanc idJoueur IDREF #REQUIRED>
        <!ELEMENT JoueurNoir EMPTY>
        <!ATTLIST JoueurNoir idJoueur IDREF #REQUIRED>
        <!ELEMENT Coups (Coup+)>
        <!ELEMENT Coup (Deplacement|Roque)>
        <!ELEMENT Deplacement (
                Depart,
                Arrivee,
                (Pion|Cavalier|Tour|Dame|Roi|Fou),
                PieceEliminee?,
                Effet?
                )>
        <!ELEMENT Depart (#PCDATA)>
        <!ELEMENT Arrivee (#PCDATA)>
        <!ELEMENT Pion (Promotion?)>
        <!ELEMENT Promotion (Cavalier|Tour|Dame|Fou)>
        <!ELEMENT Cavalier EMPTY>
        <!ELEMENT Tour EMPTY>
        <!ELEMENT Dame EMPTY>
        <!ELEMENT Roi EMPTY>
        <!ELEMENT Fou EMPTY>
        <!ELEMENT PieceEliminee (Pion|Cavalier|Tour|Dame|Fou)>
        <!ELEMENT Effet (EchecAuRoi|EchecEtMat|PartieNulle)>
        <!ELEMENT EchecAuRoi EMPTY>
        <!ELEMENT EchecEtMat EMPTY>
        <!ELEMENT PartieNulle EMPTY>
        <!ELEMENT Roque (Petit|Grand)>
        <!ELEMENT Petit EMPTY>
        <!ELEMENT Grand EMPTY>
        <!ELEMENT Score (EquipeRef, EquipeRef)>
        <!ELEMENT EquipeRef (#PCDATA)>
        <!ATTLIST EquipeRef idEquipe IDREF #REQUIRED>
        <!ELEMENT Vainqueur EMPTY>
        <!ATTLIST Vainqueur idEquipe IDREF #REQUIRED>

=== alphasigma25/SER_Labo1/src/echecs.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Organisation SYSTEM "echecs.dtd">
<Organisation>
    <Nom>Enjoy Chess</Nom>
    <Joueurs>
        <Joueur noAVS="J1">
            <noAVS>"756.1234.5678.97"</noAVS>
            <Nom>Joueur 1</Nom>
            <Prenom> </Prenom>
            <ELO>1200</ELO>
        </Joueur>
        <Joueur noAVS="J2">
            <noAVS>"756.1234.5679.97"</noAVS>
            <Nom>Joueur 2</Nom>
            <Prenom> </Prenom>
            <ELO>1200</ELO>
        </Joueur>
        <Joueur noAVS="J3">
            <noAVS>"756.1234.5689.97"</noAVS>
            <Nom>Joueur 3</Nom>
            <Prenom> </Prenom>
            <ELO>1200</ELO>
        </Joueur>
        <Joueur noAVS="J4">
            <noAVS>"756.1234.5479.97"</noAVS>
            <Nom>Joueur 4</Nom>
            <Prenom> </Prenom>
            <ELO>1200</ELO>
        </Joueur>
    </Joueurs>
    <Arbitres>
        <Arbitre id="A1">
            <Nom>Monsieur</Nom>
            <Prenom>l'arbitre</Prenom>
        </Arbitre>
        <Arbitre id="A2">
            <Nom>l'autre Monsieur</Nom>
            <Prenom>l'arbitre</Prenom>
        </Arbitre>
    </Arbitres>
    <ListeTournois>
        <ArbitresRef>
            <ArbitreRef arbitreId="A1"/>
            <ArbitreRef arbitreId="A2"/>
        </ArbitresRef>
        <Tournois idTournois="T1">
            <Nom>Mon tournois</Nom>
            <Equipes>
                <Equipe id="E1">
                    <Nom>equipe 1</Nom>
                    <JoueursRef>
                        <JoueurRef joueurId="J1"/>
                        <JoueurRef joueurId="J2"/>
                    </JoueursRef>
                </Equipe>
                <Equipe id="E2">
                    <Nom>equipe 2</Nom>
                    <JoueursRef>
                        <JoueurRef joueurId="J3"/>
                        <JoueurRef joueurId="J4"/>
                    </JoueursRef>
                </Equipe>
            </Equipes>
            <Parties>
                <Partie>
                    <Date>02-02-2002</Date>
                    <Heure>15:38</Heure>
                    <ArbitreRef arbitreId="A1"/>
                    <Echiquiers>
                        <Echiquier>
                            <premier/>
                            <JoueurBlanc idJoueur="J1"/>
                            <JoueurNoir idJoueur="J3"/>
                            <Coups>
                                <Coup>
                                    <Deplacement>
                                        <Depart>A2</Depart>
                                        <Arrivee>A3</Arrivee>
                                        <Pion>
                                            <Promotion><Tour/></Promotion>
                                        </Pion>
                                        <PieceEliminee><Pion/></PieceEliminee>
                                        <Effet><EchecAuRoi/></Effet>
                                    </Deplacement>
                                </Coup>
                                <Coup>
                                    <Roque><Grand/></Roque>
                                </Coup>
                            </Coups>
                        </Echiquier>
                        <Echiquier>
                            <deuxieme/>
                            <JoueurBlanc idJoueur="J4"/>
                            <JoueurNoir idJoueur="J2"/>
                            <Coups>
                                <Coup>
                                    <Deplacement>
                                        <Depart>B2</Depart>
                                        <Arrivee>A3</Arrivee>
                                        <Cavalier/>
                                        <PieceEliminee><Dame/></PieceEliminee>
                                        <Effet><PartieNulle/></Effet>
                                    </Deplacement>
                                </Coup>
                                <Coup>
                                    <Roque><Petit/></Roque>
                                </Coup>
                            </Coups>
                        </Echiquier>
                    </Echiquiers>
                    <Score>
                        <EquipeRef idEquipe="E1">0</EquipeRef>
                        <EquipeRef idEquipe="E2">2</EquipeRef>
                    </Score>
                </Partie>
                <Partie>
                    <Date>02-02-2002</Date>
                    <Heure>15:38</Heure>
                    <ArbitreRef arbitreId="A1"/>
                    <Echiquiers>
                        <Echiquier>
                            <premier/>
                            <JoueurBlanc idJoueur="J1"/>
                            <JoueurNoir idJoueur="J3"/>
                            <Coups>
                                <Coup>
                                    <Deplacement>
                                        <Depart>A2</Depart>
                                        <Arrivee>A3</Arrivee>
                                        <Pion/>
                                        <PieceEliminee><Cavalier/></PieceEliminee>
                                    </Deplacement>
                                </Coup>
                                <Coup>
                                    <Deplacement>
                                        <Depart>F2</Depart>
                                        <Arrivee>F3</Arrivee>
                                        <Pion/>
                                        <PieceEliminee><Cavalier/></PieceEliminee>
                                        <Effet><EchecEtMat/></Effet>
                                    </Deplacement>
                                </Coup>
                            </Coups>
                        </Echiquier>
                        <Echiquier>
                            <deuxieme/>
                            <JoueurBlanc idJoueur="J4"/>
                            <JoueurNoir idJoueur="J2"/>
                            <Coups>
                                <Coup>
                                    <Deplacement>
                                        <Depart>B2</Depart>
                                        <Arrivee>A3</Arrivee>
                                        <Cavalier/>
                                        <PieceEliminee><Tour/></PieceEliminee>
                                    </Deplacement>
                                </Coup>
                                <Coup>
                                    <Deplacement>
                                        <Depart>C2</Depart>
                                        <Arrivee>F5</Arrivee>
                                        <Fou/>
                                        <PieceEliminee><Tour/></PieceEliminee>
                                    </Deplacement>
                                </Coup>
                            </Coups>
                        </Echiquier>
                    </Echiquiers>
                    <Score>
                        <EquipeRef idEquipe="E1">0</EquipeRef>
                        <EquipeRef idEquipe="E2">2</EquipeRef>
                    </Score>
                </Partie>
            </Parties>
            <Vainqueur idEquipe="E2"/>
        </Tournois>
        <Tournois idTournois="T2">
            <Nom>Super tournois</Nom>
            <Equipes>
                <Equipe id="E3">
                    <Nom>d√©butants chanceux</Nom>
                    <JoueursRef>
                        <JoueurRef joueurId="J1"/>
                        <JoueurRef joueurId="J2"/>
                    </JoueursRef>
                </Equipe>
                <Equipe id="E4">
                    <Nom>experts malchanceux</Nom>
                    <JoueursRef>
                        <JoueurRef joueurId="J3"/>
                        <JoueurRef joueurId="J4"/>
                    </JoueursRef>
                </Equipe>
            </Equipes>
            <Parties>
                <Partie>
                    <Date>02-02-2002</Date>
                    <Heure>15:38</Heure>
                    <ArbitreRef arbitreId="A1"/>
                    <Echiquiers>
                        <Echiquier>
                            <premier/>
                            <JoueurBlanc idJoueur="J1"/>
                            <JoueurNoir idJoueur="J3"/>
                            <Coups>
                                <Coup>
                                    <Deplacement>
                                        <Depart>E2</Depart>
                                        <Arrivee>E4</Arrivee>
                                        <Pion/>
                                    </Deplacement>
                                </Coup>
                                <Coup>
                                    <Roque><Petit/></Roque>
                                </Coup>
                            </Coups>
                        </Echiquier>
                        <Echiquier>
                            <deuxieme/>
                            <JoueurBlanc idJoueur="J4"/>
                            <JoueurNoir idJoueur="J2"/>
                            <Coups>
                                <Coup>
                                    <Deplacement>
                                        <Depart>B2</Depart>
                                        <Arrivee>A3</Arrivee>
                                        <Cavalier/>
                                        <PieceEliminee><Tour/></PieceEliminee>
                                    </Deplacement>
                                </Coup>
                                <Coup>
                                    <Deplacement>
                                        <Depart>E2</Depart>
                                        <Arrivee>D3</Arrivee>
                                        <Fou/>
